<?php
/**
 * Page designs -- shipped IN the plugin, installed into Elementor's local library.
 *
 * Decision 7 (2026-09-22): one Site Template, several page designs inside it.
 * Shipping them with the plugin means a plugin update brings new or improved
 * designs to every customer site, including ones cloned months ago, with no
 * template server to run.
 *
 *   templates/*.json  -> Elementor -> Templates -> Saved Templates  (library)
 *                        Refreshed when a file's homeflip_version rises.
 *                        Customers insert them; they never edit the library copy.
 *
 *   starter pages     -> real Pages (Home, Join Our Buyers List, ...) created ONCE
 *                        and then owned by the customer. Never overwritten by an
 *                        update: a customer's edits to their Home page are theirs.
 *                        POST homeflip/v1/templates {"refresh_pages":true} rebuilds
 *                        them, for iterating on the template site before a clone.
 *
 * The JSON files are GENERATED by tools/build_templates.py. Edit that, not these.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const HOMEFLIP_TEMPLATES_OPTION = 'homeflip_templates';
const HOMEFLIP_PAGES_OPTION     = 'homeflip_pages';

/** @return array slug => decoded template file */
function homeflip_template_files() {
	$out = array();
	foreach ( (array) glob( __DIR__ . '/../templates/*.json' ) as $file ) {
		$data = json_decode( (string) file_get_contents( $file ), true );
		if ( is_array( $data ) && ! empty( $data['slug'] ) && isset( $data['content'] ) ) {
			$out[ $data['slug'] ] = $data;
		}
	}
	return $out;
}

/** Write an Elementor document onto a post. */
function homeflip_write_elementor( $post_id, $tpl, $doc_type ) {
	update_post_meta( $post_id, '_elementor_edit_mode', 'builder' );
	update_post_meta( $post_id, '_elementor_template_type', $doc_type );
	update_post_meta( $post_id, '_elementor_version', defined( 'ELEMENTOR_VERSION' ) ? ELEMENTOR_VERSION : '' );
	update_post_meta( $post_id, '_elementor_page_settings', array( 'hide_title' => 'yes' ) );
	// wp_slash: update_post_meta unslashes, which would eat the JSON's escapes.
	update_post_meta( $post_id, '_elementor_data', wp_slash( wp_json_encode( $tpl['content'] ) ) );
}

function homeflip_install_library( $force = false ) {
	$state = (array) get_option( HOMEFLIP_TEMPLATES_OPTION, array() );

	foreach ( homeflip_template_files() as $slug => $tpl ) {
		$ver = (int) ( $tpl['homeflip_version'] ?? 1 );
		$id  = isset( $state[ $slug ]['id'] ) ? (int) $state[ $slug ]['id'] : 0;

		if ( $id && get_post( $id ) && ! $force && (int) $state[ $slug ]['version'] >= $ver ) {
			continue;
		}

		$title = 'HomeFlip - ' . $tpl['title'];
		if ( ! $id || ! get_post( $id ) ) {
			$id = wp_insert_post(
				array(
					'post_type'   => 'elementor_library',
					'post_status' => 'publish',
					'post_title'  => $title,
				)
			);
			if ( is_wp_error( $id ) || ! $id ) {
				continue;
			}
			wp_set_object_terms( $id, 'page', 'elementor_library_type' );
		} else {
			wp_update_post(
				array(
					'ID'         => $id,
					'post_title' => $title,
				)
			);
		}

		homeflip_write_elementor( $id, $tpl, 'page' );
		$state[ $slug ] = array(
			'id'      => (int) $id,
			'version' => $ver,
		);
		update_option( HOMEFLIP_TEMPLATES_OPTION, $state, false );
	}
	return $state;
}

/**
 * Create the starter pages that do not exist yet ($refresh: rewrite them all).
 * Only files with a "page" block become pages.
 */
function homeflip_install_pages( $refresh = false ) {
	$pages   = (array) get_option( HOMEFLIP_PAGES_OPTION, array() );
	$created = false;

	foreach ( homeflip_template_files() as $slug => $tpl ) {
		if ( empty( $tpl['page'] ) ) {
			continue;
		}
		$id     = isset( $pages[ $slug ] ) ? (int) $pages[ $slug ] : 0;
		$exists = $id && get_post( $id ) && 'trash' !== get_post_status( $id );

		if ( $exists && ! $refresh ) {
			continue;
		}
		if ( ! $exists ) {
			// Adopt a page already at this address (WordPress ships a draft
			// /privacy-policy/). A second one would land at /privacy-policy-2/ and
			// every link in the designs would point at the wrong page.
			$same = get_page_by_path( $tpl['page']['path'] );
			if ( $same ) {
				$id      = (int) $same->ID;
				$exists  = true;
				$created = true;
				wp_update_post(
					array(
						'ID'          => $id,
						'post_status' => 'publish',
						'post_title'  => $tpl['page']['title'],
					)
				);
			}
		}
		if ( ! $exists ) {
			$id = wp_insert_post(
				array(
					'post_type'   => 'page',
					'post_status' => 'publish',
					'post_title'  => $tpl['page']['title'],
					'post_name'   => $tpl['page']['path'],
				)
			);
			if ( is_wp_error( $id ) || ! $id ) {
				continue;
			}
			$created = true;
		}

		update_post_meta( $id, '_wp_page_template', 'elementor_header_footer' );
		homeflip_write_elementor( $id, $tpl, 'wp-page' );

		$pages[ $slug ] = (int) $id;
		update_option( HOMEFLIP_PAGES_OPTION, $pages, false );

		if ( ! empty( $tpl['page']['front_page'] ) && 'page' !== get_option( 'show_on_front' ) ) {
			update_option( 'show_on_front', 'page' );
			update_option( 'page_on_front', $id );
		}
		if ( ! empty( $tpl['page']['privacy_page'] ) ) {
			update_option( 'wp_page_for_privacy_policy', $id );
		}
	}

	if ( $created || $refresh ) {
		homeflip_queue_purge();
	}
	return $pages;
}

/**
 * A neutral palette in place of Elementor's stock light-blue defaults, so the
 * designs look finished out of the box. Only replaces the STOCK colors: a
 * customer who picked their own brand colors keeps them. Every design references
 * these globals, so Site Settings -> Global Colors re-skins every page at once.
 */
function homeflip_set_default_palette() {
	$kit_id = (int) get_option( 'elementor_active_kit' );
	if ( ! $kit_id ) {
		return;
	}
	$settings = get_post_meta( $kit_id, '_elementor_page_settings', true );
	$settings = is_array( $settings ) ? $settings : array();
	$colors   = isset( $settings['system_colors'] ) ? (array) $settings['system_colors'] : array();

	$primary = '';
	foreach ( $colors as $c ) {
		if ( isset( $c['_id'] ) && 'primary' === $c['_id'] ) {
			$primary = strtoupper( (string) $c['color'] );
		}
	}
	if ( '' !== $primary && '#6EC1E4' !== $primary ) {
		return; // someone chose their own
	}

	$settings['system_colors'] = array(
		array( '_id' => 'primary', 'title' => 'Primary', 'color' => '#1E3A5F' ),     // deep navy
		array( '_id' => 'secondary', 'title' => 'Secondary', 'color' => '#F3F5F8' ), // light panel
		array( '_id' => 'text', 'title' => 'Text', 'color' => '#2B2F36' ),
		array( '_id' => 'accent', 'title' => 'Accent', 'color' => '#E8772E' ),      // call-to-action orange
	);
	update_post_meta( $kit_id, '_elementor_page_settings', $settings );
}

/**
 * Starter pages only ever appear on their own on a FRESH site (the template, and
 * so every clone). On a site that already has real pages -- whitebox.properties,
 * or a customer bringing an existing site -- installing the plugin must not add
 * five pages and swap the homepage. There, only the library is installed, and
 * pages come from POST homeflip/v1/templates on purpose.
 */
function homeflip_is_fresh_site() {
	if ( get_option( HOMEFLIP_PAGES_OPTION ) ) {
		return true; // already ours: only fill in any missing starter page
	}
	$count = wp_count_posts( 'page' );
	return ( (int) $count->publish + (int) $count->draft ) <= 5;
}

function homeflip_maybe_install_templates() {
	if ( ! current_user_can( 'manage_options' ) || ! did_action( 'elementor/loaded' ) ) {
		return;
	}
	if ( get_transient( 'homeflip_templates_lock' ) ) {
		return;
	}
	set_transient( 'homeflip_templates_lock', 1, 60 );
	homeflip_set_default_palette();
	homeflip_install_library();
	if ( homeflip_is_fresh_site() ) {
		homeflip_install_pages();
	}
	delete_transient( 'homeflip_templates_lock' );
}
add_action( 'admin_init', 'homeflip_maybe_install_templates', 20 );

/**
 * GET  /wp-json/homeflip/v1/templates -> library + page IDs
 * POST /wp-json/homeflip/v1/templates {"refresh_pages":true} -> reinstall all
 */
function homeflip_register_templates_route() {
	$admin = function () {
		return current_user_can( 'manage_options' );
	};
	register_rest_route(
		'homeflip/v1',
		'/templates',
		array(
			array(
				'methods'             => 'GET',
				'permission_callback' => $admin,
				'callback'            => function () {
					return rest_ensure_response(
						array(
							'library' => get_option( HOMEFLIP_TEMPLATES_OPTION, array() ),
							'pages'   => get_option( HOMEFLIP_PAGES_OPTION, array() ),
						)
					);
				},
			),
			array(
				'methods'             => 'POST',
				'permission_callback' => $admin,
				'callback'            => function ( WP_REST_Request $req ) {
					homeflip_set_default_palette();
					$library = homeflip_install_library( true );
					$pages   = homeflip_install_pages( (bool) $req->get_param( 'refresh_pages' ) );
					return rest_ensure_response(
						array(
							'library' => $library,
							'pages'   => $pages,
							'purged'  => homeflip_purge_caches(),
						)
					);
				},
			),
		)
	);
}
add_action( 'rest_api_init', 'homeflip_register_templates_route' );
